services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_qr
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pwd
    volumes:
      - ./postgres/db:/var/lib/postgresql/data


  backend:
      build:
        context: ./
        dockerfile: Dockerfile.local

      command: python manage.py runserver 0.0.0.0:8000
#      command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 300

      volumes:
        - ./config:/server/config
        - ./modules:/server/modules
        - ./media:/server/media
        - ./templates:/server/templates
        - ./logs:/server/logs
      ports:
        - "8000:8000"
      depends_on:
        - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend
