# Generated by Django 3.2.9 on 2022-01-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='answer_survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_answers', to='questionnaire.answersurvey', verbose_name='Ответ на опрос'),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questionnaire.question', verbose_name='Вопрос'),
        ),
    ]
